name: 'Terraform'
 
on:
  push:
    branches:
    - main
 
jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: production

    name: 'Terraform'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
    
    defaults:
      run:
        shell: bash
        working-directory: ./scripts/terraform

    steps:
    - uses: actions/checkout@v3
    - uses: hashicorp/setup-terraform@v2

    - name: Set Terraform Variables
      run: echo "$TFVARS_CONTENT" > terraform.tfvars
      env:
        TFVARS_CONTENT: ${{ secrets.TFVARS_CONTENT }}
     
    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check
      continue-on-error: true

    - name: Terraform Init
      id: init
      run: terraform init

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color
      continue-on-error: true
 
    - name: Terraform apply
      id: apply
      run: terraform apply -auto-approve